# Generated by Django 2.2.2 on 2019-06-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=1000)),
                ('fileName', models.CharField(max_length=250)),
                ('fileExt', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
