# Generated by Django 2.2.2 on 2019-06-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fileExt',
        ),
    ]
