# Generated by Django 2.2.2 on 2019-06-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0002_remove_file_fileext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileModel',
        ),
    ]
