# Generated by Django 2.2.2 on 2019-06-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0003_auto_20190620_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
